### ISSUE TITLE
Wrong date format for GET requests 

### ISSUE THREAD

**Issue by nowol** [ServiceStack/ServiceStack.Java#10]
I have a few GET requests that takes a date as a parameter (e.g.: give me all records before date X) however the Java client generate a URL with a date format that cannot be interpreted by the host. I was able to workaround a similar [issue](https://forums.servicestack.net/t/servicestack-java-guid-conversion-in-get-request/1394) with GUIDs by treating them as Strings but I cannot do this for dates.

I included my request and the generated URL below.

```
/api/json/reply/MyGetRequest?expiryDate=Wed+Nov+11+14%3A54%3A05+EST+2015
```
```
    public class MyGetRequest : IReturn<Token>
    {
        public DateTime ExpiryDate { get; set; }
    }
```

[Forum post](https://forums.servicestack.net/t/servicestack-java-wrong-date-format-for-get-requests/1627)

**Comment by nowol** [comment]
I played a bit with Gson and I did not find a clean way to get the serialized value without quotes.

The "dirty" way to fix the issue would be to replace this line (inside createUrl)
```
sb.append(URLEncoder.encode(val.toString(), "UTF-8"));
```
by
```
sb.append(URLEncoder.encode(getGson().toJson(val).replaceAll("^\\\"(.*)\\\"$", "$1"), "UTF-8"));
```
But as I said it feels a bit dirty, however it can handle any custom serialization (TimeSpan, Guid, etc).

**Comment by Layoric** [comment]
Could you show how you are creating the request with the Java client? Just want to clarify what the above suggestion is fixing for you. Ie, the actual value of `val.toString()`. I've stripped quotes from quoted values being added to the query string but want to clarify problem so I can add a test.

If the change fixes your issue, let me know and I'll package client jars for publishing.

**Comment by nowol** [comment]
I'm typing this from memory so I hope you'll excuse me if there are some typos.

```
.Net Code (I forgot that I had the IGet interface):
    public class MyGetRequest : IReturn<Token>, IGet
    {
        public DateTime ExpiryDate { get; set; }
    }
```
```
Java code:
MyGetRequest request = new MyGetRequest();
request.ExpiryDate = AddDays(new Date(), 7); // my own method that add X days to a date

JsonServiceClient client = new JsonServiceClient(SomeUrl);
Token result = client.send(request);
```

Without changes to the code, the URL generated is the following:
```
/api/json/reply/MyGetRequest?expiryDate=Wed+Nov+11+14%3A54%3A05+EST+2015
```
and you can see the issue with the date format...basically just calling "ToString()" on the object. The fix I proposed uses the Gson serialisers to format the dates and other types such as TimeSpan and UUID when they are used in the URL. The only issue with this method is that it adds quotes to the value and they have to be removed.

I'll post more information when I get back to work tomorrow.

**Comment by Layoric** [comment]
@nowol No worries. Thanks for the detailed explanation of the problem. I think I've got enough info the resolve the issue now and should have the packages out for when you get to work tomorrow. Thanks again for the quick response! :+1:

**Comment by Layoric** [comment]
Applied suggested fix and tested with GET and query string `Date` and I'm getting correct date times serialized to and from the server. 

https://github.com/ServiceStack/ServiceStack.Java/commit/cbdf07024d3876773355efde66ee6a2522018b0f

I'ved updated `client` and `android` libraries to `v1.0.20` which are now available from JCentre and Maven Central. 

Let me know if you have any issues. :+1:
