### ISSUE TITLE
Wrong exception when web service returns 404

### ISSUE THREAD

**Issue by nowol** [ServiceStack/ServiceStack.Java#11]
Hi,

I have a service that returns `null` if the requested item cannot be found.  I was expecting a `WebServiceException` object to be thrown but instead I got a NullReferenceException.

I looked at the JsonServiceClass.java and it looks like line ~203 (`JsonObject jsonObj = element.getAsJsonObject();`) is the culprit. Since my service returns nothing for a 404 the response body is empty and their is nothing to be deserialized which causes the NullReferenceException.

**Comment by Layoric** [comment]
I've fixed the null ref you've highlighted here. Once we've clarified #10 fixes will work for you, happy to push an update to the client libs :+1:
