### ISSUE TITLE
Missing basic/digest authentication in Json/AndroidServiceClient

### ISSUE THREAD

**Issue by Ravenheart** [ServiceStack/ServiceStack.Java#13]
Is there any plans to have built in support for basic/digest authentication in the JsonServiceClient/AndroidServiceClient. I've only found this solution but it looks not very nice.

http://www.codeproject.com/Articles/1006484/AndroidServiceClient-with-Authentication

**Comment by mythz** [comment]
There isn't yet, but please add feature requests to [ServiceStack's UserVoice](http://servicestack.uservoice.com/forums/176786-feature-requests) so we can track it.
