### ISSUE TITLE
Please change the RetentionPolicy of the Route attribute to Runtime, and use the Path attribute in JsonServiceClient

### ISSUE THREAD

**Issue by bramley-turner-stride** [ServiceStack/ServiceStack.Java#15]
Please change the `RetentionPolicy` of the `Route` attribute to `RUNTIME`, like this:
    @Retention(RetentionPolicy.RUNTIME)
    public @interface Route 

The problem with the current `/json/reply/<ClassName>` method of generating URLs is it is venerable to code being renamed on the server. In theory, renaming request classes in the API shouldn't matter, because the external definition of the API should be just the `Route` attribute defined in C#.

I want to be able to use the following code to generate the URL myself, but I can't at the moment because the Route attribute is not retained at runtime. If you just set the RetentionPolicy, I can do this (extending `JsonServiceClient` ):

    static String routeName(Object o){
        Route routeAnnotation=o.getClass().getAnnotation(Route.class);
        if(routeAnnotation!=null && routeAnnotation.Path().length()>0)){
            if(routeAnnotation.Path().startsWith("/"))
                return routeAnnotation.Path().substring(1,routeAnnotation.Path().length());
            return routeAnnotation.Path();
        }        
        return "json/reply/" + o.getClass().getSimpleName();
    }

    public String createUrl(Object requestDto, Map<String,String> query){
        String route = routeName(requestDto);
               
        StringBuilder sb = new StringBuilder();
        try {
            for (Field f : Utils.getSerializableFields(requestDto.getClass())) {
                Object val = f.get(requestDto);
                String replaceFormat = String.format("{%s}", f.getName());
                if(route.contains(replaceFormat)){
                    //fill in format strings in the route (eg /category/{taxon} )
                    route=route.replace(replaceFormat, URLEncoder.encode(val==null?"null":val.toString(), "UTF-8"));
                    continue;
                }
                if (val == null)
                    continue;

                sb.append(sb.length() == 0 ? "?" : "&");
                sb.append(URLEncoder.encode(f.getName(), "UTF-8"));
                sb.append("=");
                sb.append(URLEncoder.encode(val.toString(), "UTF-8"));
            }

            if (query != null) {
                for (Map.Entry<String, String> entry : query.entrySet()) {
                    String key = entry.getKey();
                    String val = entry.getValue();

                    sb.append(sb.length() == 0 ? "?" : "&");
                    sb.append(URLEncoder.encode(key, "UTF-8"));
                    sb.append("=");
                    if (val != null) {
                        sb.append(URLEncoder.encode(val, "UTF-8"));
                    }
                }
            }
        } catch (IllegalAccessException | UnsupportedEncodingException e) {
            throw new RuntimeException(e);
        }
        
        String requestUrl = this.baseUrl + route; 
        return requestUrl + sb.toString();
    }

**Comment by mythz** [comment]
We can't use the `@Route()` attribute as Java only allows 1 Route annotation and Request DTO's can support multiple attributes and we'd need to be able to select the most appropriate route so we're instead using the pre-defined roues. If the server DTO's are updated the clients can update the server DTO's which will be a compile-time error if the Request DTO is renamed. 

But as for your original request, the `@Route()` attribute [already has a retention policy of Runtime](https://github.com/ServiceStack/ServiceStack.Java/blob/master/src/AndroidClient/client/src/main/java/net/servicestack/client/Route.java#L9):

```java
@Retention(RetentionPolicy.RUNTIME)
public @interface Route { ... }
```

**Comment by bramley-turner-stride** [comment]
Thanks, it looks like that RetentionPolicy was changed after the latest release. It's not in 1.0.15.

Even if Java did support multiple annotations, you would still need to choose which route to use anyway. I'm not sure there'd be any issue in just taking the 'first' one. Any params not part of the selected route would just be added as query string params, as my example code does.

If it really does matter, you could change the Path type to an array, and supply the route index to use to JsonServiceClient.

I guess it would still be a problem if you had different routes for different verbs for the same Dto.

**Comment by mythz** [comment]
The .NET ServiceClients selects the most appropriate Route based on the state of the populated Request DTO and the HTTP Method used, it needs access to all routes to do this. Not going to have the Java client work differently to every other Service Client by randomly picking the first route which may have an incompatible verb or unpopulated path variables in the path which will end up sending an invalid url. The behavior in different states/situations wouldn't be predictable, only apply to the Java ServiceClient and would require devs to examine the source code or use a packet sniffer to infer the behavior in different situations.

If you want to change the default behavior you can inherit from JsonServiceClient and override the `createUrl()` method.
