### ISSUE TITLE
Guids deserialized with JsonSerializers do not match java.util.UUID.equals()

### ISSUE THREAD

**Issue by bramley-turner-stride** [ServiceStack/ServiceStack.Java#16]
UUIDs created with the servicestack JsonSerializers/Utils are inconsistent with java.util methods:

```
UUID javaParsed = UUID.fromString("D8EDF308-DBEB-4BE3-82F9-8B57584E381F");
UUID ssParsed = net.servicestack.client.Utils.fromGuidString("D8EDF308-DBEB-4BE3-82F9-8B57584E381F");
```
`javaParsed.toString()`:
"d8edf308-dbeb-4be3-82f9-8b57584e381f" //as expected
`ssParsed.toString()`:
"08f3edd8-ebdb-e34b-82f9-8b57584e381f" //not expected
`javaParsed.equals(ssParsed)`:
false //not expected

**Comment by mythz** [comment]
Read this thread on [Java UUID vs .NET GUIDs](https://forums.servicestack.net/t/servicestack-java-uuid-guid-conversion-inversion/1199/3?u=mythz) which do not share the same format. If you prefer you can treat .NET's GUID's as an opaque string by specifying:

/* Options:
...
TreatTypesAsStrings: Guid

*/

**Comment by bramley-turner-stride** [comment]
Interesting, thanks.
In what sense is the UUID created by ss java Utils the same as C# Guids then? Because:
C#:
`Guid.Parse("D8EDF308-DBEB-4BE3-82F9-8B57584E381F").ToByteArray()`:
[8,243,237,216,235,219,227,75,130,249,139,87,88,78,56,31]

Java:
`Utils.toGuidBytes(Utils.fromGuidString("D8EDF308-DBEB-4BE3-82F9-8B57584E381F"))` :
[-40, -19, -13, 8, -37, -21, 75, -29, -126, -7, -117, 87, 88, 78, 56, 31]

Just trying to understand the reasoning behind the particular ss Utils deserialize implementation.
SS has decided their implementation is better than emulating the same Java toString, just wondering why.

To avoid others having the same confusion, I have a feature request:
This should be a new class in Java, `Guid` (a la `TimeSpan`), that works the way C# Guid does rather than Java UUID. Because the only way to obtain the original guid string ("D8ED..") in java at the moment is to use Utils.toGuidString(), which is not obvious (and even that doesn't include dashes).

**Comment by mythz** [comment]
Here's the [test that shows the current behavior](https://github.com/ServiceStack/ServiceStack.Java/blob/a8984592ed42cb5373f0d41485320e2caa978d2d/src/AndroidClient/client/src/test/java/net/servicestack/client/tests/UtilsTests.java#L30-L39) and a link to the blog post that explains how MS GUID's and Java UUID's differ, you can see the [reordering differences clearer in Marc's answer](http://stackoverflow.com/a/18085116/85785).
