### ISSUE TITLE
overview.json is included in the apk of projects using the ServiceStack client

### ISSUE THREAD

**Issue by bramley-turner-stride** [ServiceStack/ServiceStack.Java#18]
this file:
https://github.com/ServiceStack/ServiceStack.Java/blob/master/src/AndroidClient/android/src/main/assets/overview.json

gets included in the assets dir of any apk built with the ServiceStack client.
This is not needed by the library, and increases apk size for no reason. There also doesn't seem to be an easy way to remove it without emptying the entire SS project into mine.
If you could delete it that would be great, thanks

**Comment by mythz** [comment]
Removed in this commit: https://github.com/ServiceStack/ServiceStack.Java/commit/edd6e810bf11a8e65a76f57d2fa9aa0bfcdbd3cd

we'll look at pushing a new release at the end of the week.
