### ISSUE TITLE
JsonServiceClient should prefer the @Route annotation over the /json/reply/ default endpoint

### ISSUE THREAD

**Issue by schmidt4brains** [ServiceStack/ServiceStack.Java#20]
@Layoric I'm a Java n00b, so I might not be aware other constraints on the Java library. I'd like to know your thoughts on this.

The current `JsonServiceClient` Java class will only issue requests to the `/json/reply/servicename` default endpoint, instead of using the user-defined REST route. I think this makes for a more tightly-coupled client/server design.

Consider a server code change for a service model class from version A:
```C#
[Route("/rockstars/{Id}", "GET")
public class GetRockstarRequest: IReturn<Rockstar>
{
    public int Id { get; set; }
}
```
to something like version B:
```C#
[Route("/rockstars/{Id}", "GET")
public class GetRockstar: IReturn<Rockstar>
{
    public int Id { get; set; }
}
```

All the Java clients derived from version A stop working, since they make requests to `GET /json/reply/GetRockstarRequest`, which now returns a `404` from a version B server.
All the C# clients derived from version A continue working, since they make requests to `GET /rockstars/1234`, which is still routed correctly.

I'm not aware if the ServiceStack server-side framework provides any control over specifying the name of the `servicename` portion of the `/json/reply/servicename` default endpoint. But I know that our server developers will (and should) have no fear about refactoring class names of DTOs. I'm really worried that systems will break.

If the C# and Java client DTOs are regenerated from the version B server, then the problem corrects itself, but we often have no control over the life-cycle of deployed clients.

I think the Java JsonServiceClient would be more robust if it could detect the `@Route` annotation on a request DTO and use the user-defined route (with appropriate template substitution of property values).

If I was a stronger Java developer, I would write the code and tests myself and just raise a pull request, but I'm fairly new to the whole Java ecosystem.

Does this request sound like the right thing to do?

**Comment by Layoric** [comment]
@schmidt4brains Thanks for feedback. It does differ in behaviour, I'll look into using `getDeclaredAnnotations` of the request class to see if this can be supported by Java and Android clients alike. 

Some clients will have this limitation so it's good to understand why the json/reply paths are used and and [some limitations](https://github.com/ServiceStack/ServiceStack/wiki/Add-ServiceStack-Reference#limitations) which will vary from client to client but we'll do our best to improve the development experience. I'll leave this issue open to see what options we have to improve the Java client to use the `@Route` annotation path instead. :+1:

**Comment by mythz** [comment]
Hi Doug,

All Service Clients other than the .NET Clients use the [pre-defined Routes](https://github.com/ServiceStack/ServiceStack/wiki/Routing#pre-defined-routes) as languages that have them like Java don't have the same semantics as .NET Attributes which only allow for a single annotation whilst there are other languages lack them entirely like Swift so they can't be used.

Changing the name of the Request DTO **is** a breaking change, it impacts all non .NET Add ServiceStack Reference Languages, messages published in MQs, SOAP clients generated from WSDLs, Request DTOs without Route attributes, Views Models in Razor Views, any clients consuming Service metadata (e.g. Admin UI), links to metadata pages, Custom Service Gateway implementations, all future non-HTTP Endpoints, etc. Basically Request DTOs are a fundamental concept in ServiceStack which represents your external facing Service Contract so you'll need to be careful when refactoring them.

**Comment by schmidt4brains** [comment]
Thanks for the clarifications. Now that I know that the request DTO classname is part of the service contract, I'll get our team to add some unit tests to verify that the default endpoints remain operational.

@mythz It would be nice if there was a .NET attribute for a request DTO that could be used to "alias" the servicename expected at the default endpoint. That would be a nice convention-based way to correct for an unexpected refactoring on the server side.

**Comment by bramley-turner-stride** [comment]
@schmidt4brains I have example Java code in #15 that reads the Route attribute dynamically at runtime, which is what I'm currently using.

Also note Java 8 does allow multiple annotations on the same class, so it *is* now possible to update the Java service client code to use the same routing logic as the C# clients, if @mythz was so inclined (although this Java 8 feature is only supported on Android 7+).

**Comment by schmidt4brains** [comment]
@bramley-turner-stride Thanks for the link to sample code that reads the `@Route` attribute. I didn't see the message when it was originally sent (it was lost in the daily flood of GitHub email traffic).

I have ended up implementing something similar here: https://github.com/AquaticInformatics/aquarius-sdk-java/blob/develop/src/main/java/com/aquaticinformatics/aquarius/sdk/helpers/SdkServiceClient.java#L150

@mythz and @Layoric : You may want consider incorporating some of these changes into the ServiceStack.Java repo.

I had to extend a fair bit more methods than @bramley-turner-stride's solution, in order to support all the HTTP verbs and template parameter substitution.

(My Java-n00bness is likely showing in this code. Apologies in advance).

The `SdkServiceClient` class extends `JsonServiceClient` as follows:
- If a request DTO contains exactly one `@Route` attribute, the request is sent to that path.
- Otherwise the request falls back to the `/json/reply/{RequestDtoName}` route.
- Template parameters in `/path/{parameterId}/someotherpath` routes are substituted from request DTO properties
- Added `postFileWithRequest()` methods (and the `MultipartBuilder` class) to support multi-part file upload requests, just like the .NET client library does.

Known glitches:
- The code probably has a few Java 8 lambdas that might need to be reverted in order to hit the wider Android compatibility target.
- The code that tries to set an intelligent User-agent string based on the version of the dependencies is broken. It creates a user-agent string, but not what I was intending. I'm looking into a fix.

**Comment by mythz** [comment]
Wont have time to look into this until after the next v5 release so [I've added this as a feature request](https://servicestack.uservoice.com/forums/176786-feature-requests/suggestions/31348774-update-java-serviceclient-to-use-route-s-when-poss) so we don't forget about it.

**Comment by schmidt4brains** [comment]
OK, thanks. Hopefully by then I will have sorted out by remaining known issues.
