### ISSUE TITLE
Exception thrown when parsing explicit JSON null values in ResponseStatus 

### ISSUE THREAD

**Issue by schmidt4brains** [ServiceStack/ServiceStack.Java#21]
One of our server endpoints is configured with:
```C#
JsConfig.IncludeNullValues = true;
```

When that endpoint throws an error, the `ResponseStatus` gets serialized with explicit null values.
```json
{
    "ResponseStatus": {
        "ErrorCode": "ModelNotFoundException",
        "Message": "The specified model was not found",
        "StackTrace": null,
        "Errors": [],
        "Meta": null
    }
}
```

The `Utils.createResponseStatus()` method doesn't test for `jsonElement.isJsonNull()` before calling `getAsString()` for these response properties. That causes a `java.lang.UnsupportedOperationException: JsonNull` to be thrown [here](https://github.com/ServiceStack/ServiceStack.Java/blob/master/src/AndroidClient/client/src/main/java/net/servicestack/client/Utils.java#L555).

A helper method something like this should yield the expected `ResponseStatus` instead of throwing:
```java
private String getAsStringOrNull(JsonElement jsonElement) {
    return jsonElement.isJsonNull() ? null : jsonElement.getAsString();
}
```

**Comment by Layoric** [comment]
@schmidt4brains Thanks for reporting! :+1: 

I've added the suggested fix and added a test around your example. Just going through the CI now, I'll let you know here once 1.0.26 is available from JCenter and Maven Central. Thanks again!

**Comment by Layoric** [comment]
@schmidt4brains v1.0.26 is now available from JCenter and Maven Central for both the Android and Client libraries. ServiceStackIDEA plugin will now pick up this change when adding a ServiceStack reference to a new project that does not reference the library yet. For your existing projects, simply update `build.grade` or `pom.xml` to point to the new version.

**Comment by schmidt4brains** [comment]
Works like a charm. Thanks!
