### ISSUE TITLE
Unable to use lambda expression on Func.first, ambiguous method call

### ISSUE THREAD

**Issue by bramley-turner-stride** [ServiceStack/ServiceStack.Java#23]
Most methods in `net.servicestack,func.Func` work fine with lambdas, except:
`Fare firstFare = Func.first(fares, f -> f.fareIndexNo>0);`
Ambiguous method call::
`public static <T> T first(Iterable<T> xs, Predicate<T> predicate)`
`public static <T> T first(Iterable<T> xs, T defaultValue)`
both match

I wish there was an easy change you could make to get this to work, without breaking anyone who is relying on the other `Func.first(fares, defaultIfEmpty)` method. But I can't think of a way except just duplicating the method with a new name.

Java 8 lambdas are very compatible with old versions of Android, so it's quite safe to update Android projects to use it. Old versions of Android won't have the `java.util.stream` or `java.util.function` interfaces, so I still want to use `net.servicestack,func`

**Comment by mythz** [comment]
I've renamed the `first()` with defaultValue to `firstOrDefault()` in this commit: https://github.com/ServiceStack/ServiceStack.Java/commit/002e79c42fff153cef3c459fccca94366b3331c0

It'll be available in the next release, hopefully next week.

**Comment by bramley-turner-stride** [comment]
Cheers!
