### ISSUE TITLE
KeyValuePair type translate to Java type

### ISSUE THREAD

**Issue by KevinPan** [ServiceStack/ServiceStack.Java#24]
The KeyValuePair in .Net is not translated to a java related type, it is still KeyValuePair in the generated dto file.

**Comment by mythz** [comment]
Support for exporting KeyValuePair Type was added in [this commit](https://github.com/ServiceStack/ServiceStack/commit/954952fcdbe51a52b3a529637398c90b120cac5a). 

This change is available from v4.5.7 that's now [available on MyGet](http://docs.servicestack.net/myget).
