### ISSUE TITLE
Serialization problem of Gson for some special characters(escaped)

### ISSUE THREAD

**Issue by KevinPan** [ServiceStack/ServiceStack.Java#25]
The underlying Gson of JsonServiceClient serialization escapes the characters like: ', %, =.
For example the string "Number='001'" serialized result is "Number\u003d\u0027001\u0027"

**Comment by mythz** [comment]
Disabling escaping in Gson was added in [this commit](https://github.com/ServiceStack/ServiceStack.Java/commit/f08e7915192272f00ef56c36e7d3be81e9bfacea).

It will be available in the next release of Java plugin within 1-2 weeks.

In the meantime you can disable escaping in your `JsonServiceClient` with:

```java
JsonServiceClient client = new JsonServiceClient(baseUrl);
client.setGson(getGsonBuilder().disableHtmlEscaping().create());
```
