### ISSUE TITLE
Where/what is test.dtos?

### ISSUE THREAD

**Issue by dchurchland** [ServiceStack/ServiceStack.Java#26]
In the Java net.servicestack.client:

I want to write a unit test so I can fix a bug but I am unable to get the tests to build.  I see an 'import test.dtos.*' but I cannot see a test.dtos package in the repo.

An example error:

The class Hello exists in net.servicestack.client but that is not imported to JsonServiceClientTests.java.  I can add an import statement but that assumes the code in the repo is broken.

My apologies if my lack of Java expertise is causing me to miss something.

**Comment by mythz** [comment]
It's in [test/dtos.java](https://github.com/ServiceStack/ServiceStack.Java/blob/master/src/AndroidClient/client/src/test/java/test/dtos.java), i.e. `test` is the package `dtos` is the static class containing all the DTOs.
