### ISSUE TITLE
Error parsing pre-1970 dates of format Date(-300740400000)

### ISSUE THREAD

**Issue by bramley-turner-stride** [ServiceStack/ServiceStack.Java#4]
The SS JSON date deserializer (net.servicestack.client.JsonSerializers) does not handle pre-1970 dates correctly. It throws an error 'could not convert "" to Long".

**Comment by mythz** [comment]
Right it doesn't handle Unix Timestamps before 1970 (they start at 1970). 

You can [submit a feature request for it](http://servicestack.uservoice.com/forums/176786-feature-requests).

**Comment by mythz** [comment]
Wait, just noticed this was for the Java client, I'll investigate.

**Comment by bramley-turner-stride** [comment]
It's also a problem in the swift client, btw

**Comment by mythz** [comment]
Should be fixed with this commit: https://github.com/ServiceStack/ServiceStack.Java/commit/def45350521278ba75e08c311cb3db31fe99d24d

We'll publish a new version at end of the week /cc @Layoric

**Comment by Layoric** [comment]
@bramley-turner-stride new version with fixes (1.0.15) now available via Maven Central/JCenter.
