### ISSUE TITLE
JsonServiceClient GlobalResponseFilter is not used

### ISSUE THREAD

**Issue by bramley-turner-stride** [ServiceStack/ServiceStack.Java#5]
The net.servicestack.client.JsonServiceClient.GlobalResponseFilter is never used.

**Comment by Layoric** [comment]
Could you provide some more detail of what issue you are having?

GlobalResponseFilter is fired if one is registered [here](https://github.com/ServiceStack/ServiceStack.Java/blob/b8d1f1199ee0511cb024455ebe86793b93d6782b/src/AndroidClient/client/src/main/java/net/servicestack/client/JsonServiceClient.java#L238)

If you're having a specific problem with it, you're going to have to provide an example of the problem so we can reproduce the error.

**Comment by mythz** [comment]
Also make sure you've got the latest version, we added this a while ago.

**Comment by bramley-turner-stride** [comment]
Apologies, this has been fixed since my version 1.0.1.
