### ISSUE TITLE
Default imports get mangled

### ISSUE THREAD

**Issue by bramley-turner-stride** [ServiceStack/ServiceStack.Java#6]
When I write some default imports to the java generated service reference file, they get mangled.
Eg
`DefaultImports: java.math.*,java.util.*,net.servicestack.client.*`

Running 'update ServiceStack reference' results in:

`DefaultImports: java.math.*%2Cjava.util.*%2Cnet.servicestack.client.*`
and the generated code:

`import java.math.*%2Cjava.util.*%2Cnet.servicestack.client.*;`

If I separated the imports out to a new line each, eg:
```
DefaultImports: java.math.*
DefaultImports: java.util.*
DefaultImports: net.servicestack.client.*
```
Then the code is generated correctly, but they are reverted back to a single line in the options. Updating the reference a second time then of course mangles them again.

ServiceStack Plugin v1.06
Android Studio v1.3.2

**Comment by Layoric** [comment]
@bramley-turner-stride It seems the options were being URL encoded automatically by URIBuilder.

I've packaged an updated plugin, could you confirm this solves your issue?

https://github.com/ServiceStack/ServiceStack.Java/raw/master/src/ServiceStackIDEA/ServiceStackIDEA.zip

**Comment by Layoric** [comment]
@bramley-turner-stride I've tested this with Android Studio and IntelliJ and now works. Update should be available in your IDE in 2-3 days (Jetbrains approval required for update). Please reopen the issue if you are still having the issue after updating to version 1.0.7
